CREATE DATABASE HR_EMP;
USE HR_EMP;

-- AVG SAL BY DEPT
SELECT DEPARTMENT , AVG(MONTHLYINCOME) AS 'AVGERAGE SALARY' FROM TABLE_NAME
GROUP BY DEPARTMENT;

-- COUNT OF EMP BY GENDER
SELECT GENDER, COUNT(*) AS 'COUNT_EMP_SEX' FROM TABLE_NAME
GROUP BY GENDER;

-- ATTRITION RATE OF DEP 
SELECT Department,
       COUNT(CASE WHEN Attrition = 'Yes' THEN 1 END) AS Attrition_Count,
       COUNT(*) AS Total_Employees,
       ROUND(100.0 * COUNT(CASE WHEN Attrition = 'Yes' THEN 1 END) / COUNT(*), 2) AS Attrition_Percentage
FROM TABLE_NAME
GROUP BY Department
ORDER BY Attrition_Percentage DESC;

-- JOB ROLE WITH HIGH SAL
SELECT JOBROLE, MAX(MONTHLYINCOME) AS 'HIGHEST SALARY'
FROM TABLE_NAME
GROUP BY JOBROLE
ORDER BY `HIGHEST SALARY` DESC
LIMIT 3;

-- AVG AGE BY DEPT
SELECT DEPARTMENT , AVG(AGE) AS 'AVGERAGE AGE OF EMP'
FROM TABLE_NAME
GROUP BY DEPARTMENT;

-- ATTRITION BY OVERTIME 
SELECT OVERTIME, 
COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END ) AS 'ATTRITION_COUNT',
COUNT(*) AS 'TOTAL_EMP',
100*(COUNT(CASE WHEN ATTRITION = 'YES' THEN 1 END )/COUNT(*)) AS 'ATTRITION RATE'
FROM TABLE_NAME 
GROUP BY OVERTIME;

-- AVG SAL BY GENDER & DEPT 
SELECT DEPARTMENT, GENDER , AVG(MONTHLYINCOME) AS 'SALARY'
FROM TABLE_NAME
GROUP BY  DEPARTMENT, GENDER
ORDER BY DEPARTMENT, GENDER DESC;

-- AGE GROUP DISTRIBUTION 
SELECT Department,
       CASE 
           WHEN Age BETWEEN 18 AND 25 THEN '18-25'
           WHEN Age BETWEEN 26 AND 35 THEN '26-35'
           WHEN Age BETWEEN 36 AND 45 THEN '36-45'
           ELSE '46+'
       END AS Age_Group,
       COUNT(*) AS Employee_Count
FROM TABLE_NAME
GROUP BY Department,
         CASE 
             WHEN Age BETWEEN 18 AND 25 THEN '18-25'
             WHEN Age BETWEEN 26 AND 35 THEN '26-35'
             WHEN Age BETWEEN 36 AND 45 THEN '36-45'
             ELSE '46+' 
         END
ORDER BY Department, Age_Group;

-- Compare Each Employee’s Salary to Department Average
WITH Dept_Avg AS (
    SELECT Department, ROUND(AVG(MonthlyIncome), 2) AS Dept_Avg_Salary
    FROM TABLE_NAME
    GROUP BY Department
)
SELECT e.EmployeeNumber, e.Department, e.JobRole, e.MonthlyIncome,
       d.Dept_Avg_Salary,
       CASE 
           WHEN e.MonthlyIncome > d.Dept_Avg_Salary THEN 'Above Dept Avg'
           ELSE 'Below Dept Avg'
       END AS Salary_Level
FROM TABLE_NAME e
JOIN Dept_Avg d
ON e.Department = d.Department;
